# Use postgres/example user/password credentials
version: '3.5'

services:
  backend-barista:
    container_name: barista_container
    image: barista:latest
    ports:
      - "8081:8080"
    environment:
      POSTGRESQL_IP: "postgres"
      POSTGRESQL_PORT:  "5432"
    networks:
      - barista_network
    restart: always
    depends_on:
      - postgres

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - barista_network
      - internal_network
    restart: unless-stopped

  # gitlab:
  #   image: 'gitlab/gitlab-ee:latest'
  #   restart: always
  #   hostname: 'gitlab.example.com'
  #   environment:
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'https://gitlab.example.com'
  #       # Add any other gitlab.rb configuration here, each on its own line
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #     - '22:22'
  #   networks:
  #     - internal_network
  #   volumes:
  #     - '$GITLAB_HOME/config:/etc/gitlab'
  #     - '$GITLAB_HOME/logs:/var/log/gitlab'
  #     - '$GITLAB_HOME/data:/var/opt/gitlab'
  #   shm_size: '256m'

networks:
  barista_network:
    driver: bridge
  internal_network:
    driver: bridge

volumes:
  postgres:
  # gitlab:
  


