info:
  contact:
    email: none@email.com
    name: API Support
    url: http://www.github.com/ileossa
  description: This is a poc, to learn go project.
  license:
    name: GNU AGPLv3
    url: https://spdx.org/licenses/AGPL-3.0-or-later.html
  termsOfService: http://swagger.io/terms/
  title: Swagger barista world application
  version: 0.1-beta
paths:
  /menus:
    get:
      consumes:
      - application/json
      description: list of all beverages
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: struct
      summary: GetBeverages responds with the list of all beverages as JSON
      tags:
      - Beverages
  /ping:
    get:
      description: We can check if application is up
      produces:
      - application/json
      responses:
        "200":
          description: return UP if application is ready
          schema:
            type: string
      summary: Ping
swagger: "2.0"
